### ISSUE TITLE
Заливка новых тайтлов [ВСЕ ЯЗЫКИ]

### ISSUE THREAD

**Issue by tsikha** [mrvladplotnikov/gbwp#16]
Необходимо залить новые тайтлы на страницах:
- main [все языки]
- about [все языки]
- portfolio [все языки]
- music_composing [RU/UA]
- sound_design [RU/UA] + написать слово Design с маленькой буквы [EN]
- audio_branding [RU/UA]
- voice casting [RU/UA]
- cases [RU/UA/EN] (*там внести тайтлы, отмеченные жёлтым; структуру с окончанием **| VP Production** можно оставить)

Всё нужное [в этом доке](https://docs.google.com/spreadsheets/d/13NRCKKSiErrAWpXily1w3CnLVZr3ZFJiVAYF633BLFw/edit#gid=918908590) на соответствующих листах.

**Comment by tarotum** [comment]
@tsikha тайтлы для кейсов можно заполнить из адмники, нужно зайти в Работы -> изменить работу 
и внизу страницы будет раздел SEO в нем поле title
