### ISSUE TITLE
Отсутствует изображение или подхватывается какое-то рандомное при вставке ссылки на сайт куда-либо (мессенджеры, соцсети и т.д.)

### ISSUE THREAD

**Issue by mrvladplotnikov** [mrvladplotnikov/gbwp#17]
Пример с телеграма:
![image](https://user-images.githubusercontent.com/60486240/98338082-47bcfc80-2012-11eb-84ce-33a70fb246a4.png)

Пример с LinkedIn: 
![image](https://user-images.githubusercontent.com/60486240/98338138-5c00f980-2012-11eb-85c0-87d22f4aa474.png)

Суть в том, чтобы при вставке ссылок отображалось наше лого.

**Comment by mrvladplotnikov** [comment]
Попробовал и что-то нигде не поменялось.

**Comment by tarotum** [comment]
Это потому что у них осталась старая ссылка в кэше, вот тут можно проверить https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fvp-production.com%2F
