### ISSUE TITLE
Поправить название должности клиента на странице отзывов [EN]

### ISSUE THREAD

**Issue by tsikha** [mrvladplotnikov/gbwp#21]
На англ.версии на [странице отзывов](https://vp-production.com/en/reviews), у одного из отозвавшихся (Peter Hornyak) должность написана по-русски. Поправить на Game Producer

![image](https://user-images.githubusercontent.com/73551403/100773555-b589f780-3409-11eb-84e4-6719fcef6bdb.png)

**Comment by tarotum** [comment]
Поправил ошибку в ВБ, должна быть пофикшена после следующего деплоя
