### ISSUE TITLE
Инвертировать стрелку открытия фильтров

### ISSUE THREAD

**Issue by mrvladplotnikov** [mrvladplotnikov/gbwp#76]
После слова "Фильтры:" есть стрелка. Её нужно инвертировать. Чтобы показывала вниз при закрытом состоянии и вверх при открытом (когда видны фильтры).

**Comment by tarotum** [comment]
![image](https://user-images.githubusercontent.com/25140542/209861238-81738065-dac9-4bcf-8ebd-c80407746191.png)

![image](https://user-images.githubusercontent.com/25140542/209861206-96a92e1e-2aef-4b6f-af42-1efeafe3a483.png)
